title: Agency - Start Bootstrap Theme
description: ''
author: ''

sass: # Enables the conversion of css/agency.min.scss to  css/agency.min.css
  style: compressed

assets_path: '' 

collections: # Enables additional data structures 
  projects: # Enables _projects

theme: jekyll-theme-startbootstrap-agency