url: https://yingjiebyron.github.io
baseurl: /byron.GitHub.io/

# Site settings
title: Byron's Profile
email: yingjie_li@mymail.sutd.edu.sg
description: "This is a 101 profile for the learning journey in data science and what-about for Byron (Yingjie)"


# Team names, titles and social links
people:
- name: Byron (Yingjie) Li
  pic: 1
  position: Data science enthusiast
  social:
    - title: linkedIn
      url: https://www.linkedin.com/in/yingjie-li-82a6b6160/
    - title: github
      url: https://github.com/yingjiebyron


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    - title: linkedIn
      url: https://www.linkedin.com/in/yingjie-li-82a6b6160/
    - title: github
      url: https://github.com/yingjiebyron

# Postal address (add as many lines as necessary)
address:
  - line: 11 Bedok Reservoir View
  - line: Singapore 478931

# Build settings
markdown: kramdown
permalink: pretty